name: wf-ci

env:
  DOCKERHUB_ID: 'armck'


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


defaults:
  run:
    shell: bash

jobs:
  
  container-build-and-push:
    uses: armckinney/cicd/.github/workflows/rwf-container-build-and-push.yaml@main

  lint:
    runs-on: ubuntu-latest
    needs: [container-build-and-push]
    container:
      image: ${{ needs.container-build-and-push.outputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verify Go
      run: go version

    - name: Go Vet
      run: go vet ./...

    - name: Go Fmt Check
      run: |
        if [ -n "$(gofmt -l .)" ]; then
          echo "Run gofmt to fix formatting:"
          gofmt -l .
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    needs: [container-build-and-push]
    container:
      image: ${{ needs.container-build-and-push.outputs.container_image }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Tests
      run: go test ./... -v
